services:
  - type: web
    name: us-be-api
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    env: production
    envVars:
      - key: DATABASE_URL
      - key: JWT_SECRET  
      - key: EMAIL_USER
      - key: EMAIL_PASS